### PR TITLE
chore: Add workflow for CheckStyle

### PR DESCRIPTION
**Pull request by richard-bogdan-bitrise**
Added workflow for CheckStyle named 'check_code_formatting': it will run
 checkstyle and upload the reports to bitrise.io.

APM-2636

### CODE REVIEW

**Comment by richard-bogdan-bitrise** [comment]
Note:branched from APM-2638

**Comment by richard-bogdan-bitrise** [comment]
To check how it works, please see any build of primary_v2, and check the uploaded data.

**Comment by daniellevass-bitrise** [comment]
> To check how it works, please see any build of primary_v2, and check the uploaded data.

This confused me greatly - i checked the outputs of this branch on primary_v2 and didn't see any outputs e.g. https://app.bitrise.io/build/a29a29a61d8c52e6#?tab=log but saw there were on APM-2626 e.g. https://app.bitrise.io/build/75646292a384c2c8#?tab=log

Your comment would have been more helpful if you'd said the work to integrate it into primary was done in another branch - or if you'd posted a screengrab of what the expected output would look like.

I understand the report shows that we have several thousand conflicts - How will this affect our build status? If we increase it does it fail our build? Or is this a manual process we have to check regularly to see if things are increasing/decreasing?

**Review by daniellevass-bitrise — APPROVED** [review]
Code looks fine - left a question regarding whether the reports.

**Comment by richard-bogdan-bitrise** [comment]
> > To check how it works, please see any build of primary_v2, and check the uploaded data.
> 
> This confused me greatly - i checked the outputs of this branch on primary_v2 and didn't see any outputs e.g. https://app.bitrise.io/build/a29a29a61d8c52e6#?tab=log but saw there were on [APM-2626](https://bitrise.atlassian.net/browse/APM-2626) e.g. https://app.bitrise.io/build/75646292a384c2c8#?tab=log
> 
> Your comment would have been more helpful if you'd said the work to integrate it into primary was done in another branch - or if you'd posted a screengrab of what the expected output would look like.
> 
> I understand the report shows that we have several thousand conflicts - How will this affect our build status? If we increase it does it fail our build? Or is this a manual process we have to check regularly to see if things are increasing/decreasing?

This task is for adding creating a workflow to create the reports, there is a [different one](https://github.com/bitrise-io/trace-android-sdk/pull/203) to integrate it to the primary_v2 workflow.

The goal is to detect the formatting issues, and fail the build if there is any (as described in the Jira ticket), we won't have to check it automatically.

**Pull request merged**
